// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Api.AppDbContext;

#nullable disable

namespace Shop_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240516163453_gendata")]
    partial class gendata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shop_Models.Dto.SanPhamYeuThichViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<double?>("GiaThucTe")
                        .HasColumnType("float");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPhamCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiCTSP")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiND")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VerificationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SanPhamYeuThichViewModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4ae6473-7741-45ff-bc9f-7590d70f2447"),
                            AnhSanPham = "URL0",
                            ChiTietSanPhamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenSanPham = "TSP0",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("56de4bc5-e91e-4706-ba5c-21a0885d2544"),
                            AnhSanPham = "URL1",
                            ChiTietSanPhamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenSanPham = "TSP1",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fbf75ed9-fa0a-4b6f-817a-e598daaecf06"),
                            AnhSanPham = "URL2",
                            ChiTietSanPhamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenSanPham = "TSP2",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("56e86558-da30-4f6f-a442-f27b029fabeb"),
                            AnhSanPham = "URL3",
                            ChiTietSanPhamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenSanPham = "TSP3",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("32520ad3-39d8-4a81-a6dd-a3fbf128aaef"),
                            AnhSanPham = "URL4",
                            ChiTietSanPhamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenSanPham = "TSP4",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Anh", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.HasIndex("ChiTietSanPhamId");

                    b.ToTable("Anh");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4dd0cc87-767c-495b-b925-57e68e8a1628"),
                            ChiTietSanPhamId = new Guid("615ff1b2-dcd2-4a85-a66e-3a75e3d4ee9f"),
                            MaAnh = "MA0",
                            URL = "URL0"
                        },
                        new
                        {
                            Guid = new Guid("e268fa30-4f64-4037-9312-c559ec38aa3a"),
                            ChiTietSanPhamId = new Guid("9fc49348-853b-4420-89bd-cf9b1e0bac6d"),
                            MaAnh = "MA1",
                            URL = "URL1"
                        },
                        new
                        {
                            Guid = new Guid("792e6f5e-2e1b-404f-b241-43e86b792dfa"),
                            ChiTietSanPhamId = new Guid("15787cc5-1116-4f68-aa0e-f591cdb1ef96"),
                            MaAnh = "MA2",
                            URL = "URL2"
                        },
                        new
                        {
                            Guid = new Guid("5233ce9d-de98-4dec-a731-1c7f40333e0a"),
                            ChiTietSanPhamId = new Guid("1dfbf615-38e7-491e-b593-f59422a4bc06"),
                            MaAnh = "MA3",
                            URL = "URL3"
                        },
                        new
                        {
                            Guid = new Guid("66c6a2fb-19c9-44e4-9171-c2d2f248e92e"),
                            ChiTietSanPhamId = new Guid("d1e19dbe-8285-4ca7-b469-e67019a13aab"),
                            MaAnh = "MA4",
                            URL = "URL4"
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChatLieu", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChatLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("ChatLieu");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("cb1c36d6-ae8e-4212-ae3c-7b44b6aab686"),
                            MaChatLieu = "MCL0",
                            TenChatLieu = "TCL0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("584f9f24-001e-4aad-826f-b5f4b710945f"),
                            MaChatLieu = "MCL1",
                            TenChatLieu = "TCL1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("a781c9ce-0609-4cf5-9016-57bd3230fb0d"),
                            MaChatLieu = "MCL2",
                            TenChatLieu = "TCL2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("b84d31ac-9d63-481b-8027-1a074698bb84"),
                            MaChatLieu = "MCL3",
                            TenChatLieu = "TCL3",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("b29383d8-b17a-4572-8166-c94fe0382548"),
                            MaChatLieu = "MCL4",
                            TenChatLieu = "TCL4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietKhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhuyenMaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("KhuyenMaiId");

                    b.ToTable("ChiTietKhuyenMai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b45c0578-2bc2-46f7-8bd0-3f4ef459308b"),
                            ChiTietSanPhamId = new Guid("615ff1b2-dcd2-4a85-a66e-3a75e3d4ee9f"),
                            KhuyenMaiId = new Guid("a2dda9d4-ad65-4690-86d4-e001b699ba5f"),
                            Mota = "MTCTKM0",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("710cb96c-d29c-406f-9997-680b90ebf8fd"),
                            ChiTietSanPhamId = new Guid("9fc49348-853b-4420-89bd-cf9b1e0bac6d"),
                            KhuyenMaiId = new Guid("6e4c0a24-0a37-4ccf-b913-57f14702a4d2"),
                            Mota = "MTCTKM1",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("7484b868-a82d-4c9a-9720-78162ed16384"),
                            ChiTietSanPhamId = new Guid("15787cc5-1116-4f68-aa0e-f591cdb1ef96"),
                            KhuyenMaiId = new Guid("23830357-bf3e-4ceb-8fb3-551da0f321ab"),
                            Mota = "MTCTKM2",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("32e0d208-ad8a-480c-b64f-c7f08372873d"),
                            ChiTietSanPhamId = new Guid("1dfbf615-38e7-491e-b593-f59422a4bc06"),
                            KhuyenMaiId = new Guid("65e73287-17ea-444b-aa88-c5b37c27d2e7"),
                            Mota = "MTCTKM3",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("a499e0f4-fe1e-46dc-9284-a77fcb63a9e0"),
                            ChiTietSanPhamId = new Guid("d1e19dbe-8285-4ca7-b469-e67019a13aab"),
                            KhuyenMaiId = new Guid("07e54863-9fd0-4b0c-987c-6ba69fecf361"),
                            Mota = "MTCTKM4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<double?>("GiaThucTe")
                        .HasColumnType("float");

                    b.Property<Guid?>("LoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MauSacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<Guid?>("ThuongHieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<Guid?>("XuatXuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatLieuId");

                    b.HasIndex("LoaiId");

                    b.HasIndex("MauSacId");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("ThuongHieuId");

                    b.HasIndex("XuatXuId");

                    b.ToTable("ChiTietSanPham");

                    b.HasData(
                        new
                        {
                            Id = new Guid("615ff1b2-dcd2-4a85-a66e-3a75e3d4ee9f"),
                            ChatLieuId = new Guid("cb1c36d6-ae8e-4212-ae3c-7b44b6aab686"),
                            GiaBan = 773490.0,
                            GiaNhap = 439904.0,
                            GiaThucTe = 245721.0,
                            LoaiId = new Guid("df1d404e-a91c-4f04-b122-8264a508b8e3"),
                            MaSanPham = "SP0",
                            MauSacId = new Guid("fdbbaab8-34d6-4640-8f10-c2046829451a"),
                            Mota = "mo ta0",
                            SanPhamId = new Guid("54599620-ed04-4020-ab32-91a6db9dcde4"),
                            SoLuongDaBan = 0,
                            SoLuongTon = 0,
                            ThuongHieuId = new Guid("8f1cff3e-47cf-400b-a43e-acce4c031ab6"),
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            XuatXuId = new Guid("3a8b5061-df10-413f-9882-cf7fcca75fc3")
                        },
                        new
                        {
                            Id = new Guid("9fc49348-853b-4420-89bd-cf9b1e0bac6d"),
                            ChatLieuId = new Guid("584f9f24-001e-4aad-826f-b5f4b710945f"),
                            GiaBan = 463184.0,
                            GiaNhap = 275522.0,
                            GiaThucTe = 386531.0,
                            LoaiId = new Guid("a0b91fbf-bd40-454f-a94e-7c754e818cab"),
                            MaSanPham = "SP1",
                            MauSacId = new Guid("f440a547-e36e-4276-8535-31b52174cbce"),
                            Mota = "mo ta1",
                            SanPhamId = new Guid("35b6bc42-831d-41a3-8ca2-9e9403abff3f"),
                            SoLuongDaBan = 1,
                            SoLuongTon = 1,
                            ThuongHieuId = new Guid("cb3f7283-8348-4553-8a9e-29e827b36329"),
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 1,
                            XuatXuId = new Guid("6e1d14fa-e4c5-419a-924b-6e14d2a1f519")
                        },
                        new
                        {
                            Id = new Guid("15787cc5-1116-4f68-aa0e-f591cdb1ef96"),
                            ChatLieuId = new Guid("a781c9ce-0609-4cf5-9016-57bd3230fb0d"),
                            GiaBan = 974889.0,
                            GiaNhap = 463713.0,
                            GiaThucTe = 510728.0,
                            LoaiId = new Guid("1ef043d1-37b2-4fb4-aad9-ea5d00939bc6"),
                            MaSanPham = "SP2",
                            MauSacId = new Guid("c7d3f38b-5968-4c0b-8790-68108b1b8621"),
                            Mota = "mo ta2",
                            SanPhamId = new Guid("a0c8dc5c-dac3-4d71-8fe4-e17be1bc10c5"),
                            SoLuongDaBan = 2,
                            SoLuongTon = 2,
                            ThuongHieuId = new Guid("b88bf1da-0b62-42b9-bb12-1376a602c077"),
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 1,
                            XuatXuId = new Guid("4065adf3-e809-4d19-8613-a5fa5ab9e93c")
                        },
                        new
                        {
                            Id = new Guid("1dfbf615-38e7-491e-b593-f59422a4bc06"),
                            ChatLieuId = new Guid("b84d31ac-9d63-481b-8027-1a074698bb84"),
                            GiaBan = 142970.0,
                            GiaNhap = 618620.0,
                            GiaThucTe = 996704.0,
                            LoaiId = new Guid("1df6af10-f977-4db0-9f50-a135ddcdfd83"),
                            MaSanPham = "SP3",
                            MauSacId = new Guid("15e45203-d243-4659-951c-22b8f1a4dc7d"),
                            Mota = "mo ta3",
                            SanPhamId = new Guid("f83c0a33-922e-4a61-99b7-dc31bd14bf5a"),
                            SoLuongDaBan = 3,
                            SoLuongTon = 3,
                            ThuongHieuId = new Guid("0f497143-dbd8-4a75-8554-cd8bbee260af"),
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            XuatXuId = new Guid("388e582e-e112-487a-8f7e-0dea24ea7421")
                        },
                        new
                        {
                            Id = new Guid("d1e19dbe-8285-4ca7-b469-e67019a13aab"),
                            ChatLieuId = new Guid("b29383d8-b17a-4572-8166-c94fe0382548"),
                            GiaBan = 206664.0,
                            GiaNhap = 800041.0,
                            GiaThucTe = 731068.0,
                            LoaiId = new Guid("5b70e17d-1426-4b52-9de7-8a68b4717bb7"),
                            MaSanPham = "SP4",
                            MauSacId = new Guid("74e0b1cb-a556-4bb7-8f20-eb6608d5f6d3"),
                            Mota = "mo ta4",
                            SanPhamId = new Guid("1c5b395a-1eee-48e4-89e5-c39edee15b28"),
                            SoLuongDaBan = 4,
                            SoLuongTon = 4,
                            ThuongHieuId = new Guid("7d3a3690-9963-440d-8369-2b9998564464"),
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 1,
                            XuatXuId = new Guid("5fa71732-6655-4df3-9da8-926be46b3c3b")
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHang", b =>
                {
                    b.Property<Guid>("IdGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdGh");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("GioHang");

                    b.HasData(
                        new
                        {
                            IdGh = new Guid("8cc9ae39-9257-40f8-82c5-145f49b80ba0"),
                            IdNguoiDung = new Guid("55d1353d-42be-4acb-a345-b920295d24dc"),
                            TrangThai = 1
                        },
                        new
                        {
                            IdGh = new Guid("7003b01f-0bb5-4100-91f7-68131a86712d"),
                            IdNguoiDung = new Guid("a5a5b1fb-5ab6-49de-b376-9d6cfddc502f"),
                            TrangThai = 1
                        },
                        new
                        {
                            IdGh = new Guid("8f849e54-340d-4e0b-b84e-f144747d5313"),
                            IdNguoiDung = new Guid("a3383fbf-0883-4950-bb9f-87cb31040d44"),
                            TrangThai = 0
                        },
                        new
                        {
                            IdGh = new Guid("1c6950d0-f548-404c-84fb-321c059f9629"),
                            IdNguoiDung = new Guid("35172428-03d8-489d-ba34-a35534dcd22b"),
                            TrangThai = 1
                        },
                        new
                        {
                            IdGh = new Guid("b0ddbe55-9753-4ba7-8345-e0c7afb8c2d6"),
                            IdNguoiDung = new Guid("abf2e001-7e62-42f8-b531-6c33b2d38a98"),
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double>("GiaGoc")
                        .HasColumnType("float");

                    b.Property<Guid>("GioHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("GioHangId");

                    b.ToTable("GioHangChiTiet");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiDoHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayShip")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double>("TienShip")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<int>("TrangThaiGiaoHang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("VoucherId");

                    b.ToTable("HoaDon");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14101749-75f7-47f9-99d4-b3f597af039c"),
                            LiDoHuy = "ly do huy0",
                            MaHoaDon = "HD0",
                            MoTa = "mo ta0",
                            NgayGiaoDuKien = new DateTime(2024, 5, 27, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8407),
                            NgayNhan = new DateTime(2024, 5, 28, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8404),
                            NgayShip = new DateTime(2024, 5, 17, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8403),
                            NgayTao = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8402),
                            NgayThanhToan = new DateTime(2024, 5, 21, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8402),
                            TienGiam = 85510.0,
                            TienShip = 48285.0,
                            TongTien = 236173.0,
                            TrangThaiGiaoHang = 1,
                            TrangThaiThanhToan = 1
                        },
                        new
                        {
                            Id = new Guid("470dd866-f29e-4bcd-80b4-29f937cdf060"),
                            LiDoHuy = "ly do huy1",
                            MaHoaDon = "HD1",
                            MoTa = "mo ta1",
                            NgayGiaoDuKien = new DateTime(2024, 5, 28, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8744),
                            NgayNhan = new DateTime(2024, 5, 27, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8742),
                            NgayShip = new DateTime(2024, 5, 22, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8742),
                            NgayTao = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8741),
                            NgayThanhToan = new DateTime(2024, 5, 21, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8741),
                            TienGiam = 79327.0,
                            TienShip = 11909.0,
                            TongTien = 831937.0,
                            TrangThaiGiaoHang = 0,
                            TrangThaiThanhToan = 1
                        },
                        new
                        {
                            Id = new Guid("077d1f6c-349c-4625-9cea-829cf965252b"),
                            LiDoHuy = "ly do huy2",
                            MaHoaDon = "HD2",
                            MoTa = "mo ta2",
                            NgayGiaoDuKien = new DateTime(2024, 5, 23, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8933),
                            NgayNhan = new DateTime(2024, 5, 25, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8931),
                            NgayShip = new DateTime(2024, 5, 19, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8931),
                            NgayTao = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8930),
                            NgayThanhToan = new DateTime(2024, 5, 22, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8930),
                            TienGiam = 40611.0,
                            TienShip = 34904.0,
                            TongTien = 944161.0,
                            TrangThaiGiaoHang = 0,
                            TrangThaiThanhToan = 1
                        },
                        new
                        {
                            Id = new Guid("749ebe10-465a-4267-899b-dcfd38e49605"),
                            LiDoHuy = "ly do huy3",
                            MaHoaDon = "HD3",
                            MoTa = "mo ta3",
                            NgayGiaoDuKien = new DateTime(2024, 5, 25, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9111),
                            NgayNhan = new DateTime(2024, 5, 24, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9109),
                            NgayShip = new DateTime(2024, 5, 22, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9109),
                            NgayTao = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9108),
                            NgayThanhToan = new DateTime(2024, 5, 21, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9108),
                            TienGiam = 62575.0,
                            TienShip = 28000.0,
                            TongTien = 476297.0,
                            TrangThaiGiaoHang = 0,
                            TrangThaiThanhToan = 0
                        },
                        new
                        {
                            Id = new Guid("3173edf6-1311-45f1-914b-e9898d9261ed"),
                            LiDoHuy = "ly do huy4",
                            MaHoaDon = "HD4",
                            MoTa = "mo ta4",
                            NgayGiaoDuKien = new DateTime(2024, 5, 23, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9353),
                            NgayNhan = new DateTime(2024, 5, 28, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9351),
                            NgayShip = new DateTime(2024, 5, 19, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9351),
                            NgayTao = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9350),
                            NgayThanhToan = new DateTime(2024, 5, 20, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9350),
                            TienGiam = 65141.0,
                            TienShip = 49737.0,
                            TongTien = 346804.0,
                            TrangThaiGiaoHang = 0,
                            TrangThaiThanhToan = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("HoaDonChiTiet");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("a05051e9-303e-4a89-9df6-8046f3f3b919"),
                            ChiTietSanPhamId = new Guid("615ff1b2-dcd2-4a85-a66e-3a75e3d4ee9f"),
                            GiaBan = 668757.0,
                            HoaDonId = new Guid("14101749-75f7-47f9-99d4-b3f597af039c"),
                            SoLuong = 62
                        },
                        new
                        {
                            Guid = new Guid("804783c6-ec3f-489e-853b-e5e133f317e5"),
                            ChiTietSanPhamId = new Guid("9fc49348-853b-4420-89bd-cf9b1e0bac6d"),
                            GiaBan = 483200.0,
                            HoaDonId = new Guid("470dd866-f29e-4bcd-80b4-29f937cdf060"),
                            SoLuong = 38
                        },
                        new
                        {
                            Guid = new Guid("2da46e80-b26e-4d06-b1e6-d4c63c817300"),
                            ChiTietSanPhamId = new Guid("15787cc5-1116-4f68-aa0e-f591cdb1ef96"),
                            GiaBan = 753123.0,
                            HoaDonId = new Guid("077d1f6c-349c-4625-9cea-829cf965252b"),
                            SoLuong = 54
                        },
                        new
                        {
                            Guid = new Guid("9f3638f3-a220-4fdc-9c2a-afe722be690c"),
                            ChiTietSanPhamId = new Guid("1dfbf615-38e7-491e-b593-f59422a4bc06"),
                            GiaBan = 715665.0,
                            HoaDonId = new Guid("749ebe10-465a-4267-899b-dcfd38e49605"),
                            SoLuong = 43
                        },
                        new
                        {
                            Guid = new Guid("99f9b834-f0e6-4981-bb57-d0160ed86e77"),
                            ChiTietSanPhamId = new Guid("d1e19dbe-8285-4ca7-b469-e67019a13aab"),
                            GiaBan = 947471.0,
                            HoaDonId = new Guid("3173edf6-1311-45f1-914b-e9898d9261ed"),
                            SoLuong = 21
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Khuyenmai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiHinhKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MucGiam")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Khuyenmai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2dda9d4-ad65-4690-86d4-e001b699ba5f"),
                            LoaiHinhKhuyenMai = "LHKM0",
                            MaKhuyenMai = "MKM0",
                            MucGiam = 83.0,
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8322),
                            NgayKetThuc = new DateTime(2024, 6, 2, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8324),
                            TenKhuyenMai = "TKM0",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("6e4c0a24-0a37-4ccf-b913-57f14702a4d2"),
                            LoaiHinhKhuyenMai = "LHKM1",
                            MaKhuyenMai = "MKM1",
                            MucGiam = 25.0,
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8709),
                            NgayKetThuc = new DateTime(2024, 6, 10, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8709),
                            TenKhuyenMai = "TKM1",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("23830357-bf3e-4ceb-8fb3-551da0f321ab"),
                            LoaiHinhKhuyenMai = "LHKM2",
                            MaKhuyenMai = "MKM2",
                            MucGiam = 17.0,
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8897),
                            NgayKetThuc = new DateTime(2024, 6, 9, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8898),
                            TenKhuyenMai = "TKM2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("65e73287-17ea-444b-aa88-c5b37c27d2e7"),
                            LoaiHinhKhuyenMai = "LHKM3",
                            MaKhuyenMai = "MKM3",
                            MucGiam = 91.0,
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9076),
                            NgayKetThuc = new DateTime(2024, 5, 26, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9077),
                            TenKhuyenMai = "TKM3",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("07e54863-9fd0-4b0c-987c-6ba69fecf361"),
                            LoaiHinhKhuyenMai = "LHKM4",
                            MaKhuyenMai = "MKM4",
                            MucGiam = 44.0,
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9290),
                            NgayKetThuc = new DateTime(2024, 5, 24, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9291),
                            TenKhuyenMai = "TKM4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Loai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df1d404e-a91c-4f04-b122-8264a508b8e3"),
                            MaLoai = "ML0",
                            TenLoai = "TL0",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a0b91fbf-bd40-454f-a94e-7c754e818cab"),
                            MaLoai = "ML1",
                            TenLoai = "TL1",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("1ef043d1-37b2-4fb4-aad9-ea5d00939bc6"),
                            MaLoai = "ML2",
                            TenLoai = "TL2",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("1df6af10-f977-4db0-9f50-a135ddcdfd83"),
                            MaLoai = "ML3",
                            TenLoai = "TL3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("5b70e17d-1426-4b52-9de7-8a68b4717bb7"),
                            MaLoai = "ML4",
                            TenLoai = "TL4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("fdbbaab8-34d6-4640-8f10-c2046829451a"),
                            MaMauSac = "MMS0",
                            TenMauSac = "TMS0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("f440a547-e36e-4276-8535-31b52174cbce"),
                            MaMauSac = "MMS1",
                            TenMauSac = "TMS1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("c7d3f38b-5968-4c0b-8790-68108b1b8621"),
                            MaMauSac = "MMS2",
                            TenMauSac = "TMS2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("15e45203-d243-4659-951c-22b8f1a4dc7d"),
                            MaMauSac = "MMS3",
                            TenMauSac = "TMS3",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("74e0b1cb-a556-4bb7-8f20-eb6608d5f6d3"),
                            MaMauSac = "MMS4",
                            TenMauSac = "TMS4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VerificationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55d1353d-42be-4acb-a345-b920295d24dc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b58937d-3cc2-4549-a27a-e11b6c26e6ae",
                            DiaChi = "DC0",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND0",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null0",
                            TenNguoiDung = "TND0",
                            TrangThai = 1,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC0",
                            VerificationCodeExpiry = new DateTime(2024, 5, 18, 9, 34, 52, 687, DateTimeKind.Utc).AddTicks(8374)
                        },
                        new
                        {
                            Id = new Guid("a5a5b1fb-5ab6-49de-b376-9d6cfddc502f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f00b18c-7780-4e23-b1cb-7d7ad6f896b0",
                            DiaChi = "DC1",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND1",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null1",
                            TenNguoiDung = "TND1",
                            TrangThai = 1,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC1",
                            VerificationCodeExpiry = new DateTime(2024, 5, 18, 10, 34, 52, 687, DateTimeKind.Utc).AddTicks(8729)
                        },
                        new
                        {
                            Id = new Guid("a3383fbf-0883-4950-bb9f-87cb31040d44"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09b18bf1-07a0-41cd-af9b-74f9ddd60a8c",
                            DiaChi = "DC2",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND2",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null2",
                            TenNguoiDung = "TND2",
                            TrangThai = 1,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC2",
                            VerificationCodeExpiry = new DateTime(2024, 5, 16, 21, 34, 52, 687, DateTimeKind.Utc).AddTicks(8917)
                        },
                        new
                        {
                            Id = new Guid("35172428-03d8-489d-ba34-a35534dcd22b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed0b1dfe-e6a4-4ad1-987b-028de7b53e4c",
                            DiaChi = "DC3",
                            EmailConfirmed = false,
                            GioiTinh = true,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND3",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null3",
                            TenNguoiDung = "TND3",
                            TrangThai = 1,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC3",
                            VerificationCodeExpiry = new DateTime(2024, 5, 18, 4, 34, 52, 687, DateTimeKind.Utc).AddTicks(9096)
                        },
                        new
                        {
                            Id = new Guid("abf2e001-7e62-42f8-b531-6c33b2d38a98"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9aa0ae64-d8f2-4926-b68a-440986844291",
                            DiaChi = "DC4",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND4",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null4",
                            TenNguoiDung = "TND4",
                            TrangThai = 0,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC4",
                            VerificationCodeExpiry = new DateTime(2024, 5, 18, 1, 34, 52, 687, DateTimeKind.Utc).AddTicks(9332)
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMaPTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a6e5fbe-b6ee-4a96-91af-9c9a7d7732c7"),
                            MaPTThanhToan = "MPTTT0",
                            MoTa = "MTPTTT0",
                            TenMaPTThanhToan = "TPTTT0",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("fbccf473-a33f-4a3c-8965-6808706865d9"),
                            MaPTThanhToan = "MPTTT1",
                            MoTa = "MTPTTT1",
                            TenMaPTThanhToan = "TPTTT1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("f2fee31e-c5a6-4fe5-8684-6910143a03d0"),
                            MaPTThanhToan = "MPTTT2",
                            MoTa = "MTPTTT2",
                            TenMaPTThanhToan = "TPTTT2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("eb995848-ccae-47b1-891a-445c9319179b"),
                            MaPTThanhToan = "MPTTT3",
                            MoTa = "MTPTTT3",
                            TenMaPTThanhToan = "TPTTT3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("b67e69cb-60db-440e-9a0f-6fad7e8b6c4b"),
                            MaPTThanhToan = "MPTTT4",
                            MoTa = "MTPTTT4",
                            TenMaPTThanhToan = "TPTTT4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucTTChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PTTToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhuongThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SoTien")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("PhuongThucTTChiTiet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9167f10f-ed66-44fd-9182-3bc792427556"),
                            HoaDonId = new Guid("14101749-75f7-47f9-99d4-b3f597af039c"),
                            PTTToanId = new Guid("4a6e5fbe-b6ee-4a96-91af-9c9a7d7732c7"),
                            SoTien = 734339.0,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("2b5e64a0-bcad-4b7d-b652-aad575245868"),
                            HoaDonId = new Guid("470dd866-f29e-4bcd-80b4-29f937cdf060"),
                            PTTToanId = new Guid("fbccf473-a33f-4a3c-8965-6808706865d9"),
                            SoTien = 986825.0,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("587b7ac4-c3cb-48e9-997c-276614ea84ae"),
                            HoaDonId = new Guid("077d1f6c-349c-4625-9cea-829cf965252b"),
                            PTTToanId = new Guid("f2fee31e-c5a6-4fe5-8684-6910143a03d0"),
                            SoTien = 943778.0,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("dc4a9b62-442d-4369-be71-52fc414a52d3"),
                            HoaDonId = new Guid("749ebe10-465a-4267-899b-dcfd38e49605"),
                            PTTToanId = new Guid("eb995848-ccae-47b1-891a-445c9319179b"),
                            SoTien = 857646.0,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("11257592-911a-4e02-bd3a-56e72eb37388"),
                            HoaDonId = new Guid("3173edf6-1311-45f1-914b-e9898d9261ed"),
                            PTTToanId = new Guid("b67e69cb-60db-440e-9a0f-6fad7e8b6c4b"),
                            SoTien = 689724.0,
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdSanPham");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            IdSanPham = new Guid("54599620-ed04-4020-ab32-91a6db9dcde4"),
                            MaSanPham = "SP0",
                            TenSanPham = "TSP0",
                            TrangThai = 1
                        },
                        new
                        {
                            IdSanPham = new Guid("35b6bc42-831d-41a3-8ca2-9e9403abff3f"),
                            MaSanPham = "SP1",
                            TenSanPham = "TSP1",
                            TrangThai = 0
                        },
                        new
                        {
                            IdSanPham = new Guid("a0c8dc5c-dac3-4d71-8fe4-e17be1bc10c5"),
                            MaSanPham = "SP2",
                            TenSanPham = "TSP2",
                            TrangThai = 1
                        },
                        new
                        {
                            IdSanPham = new Guid("f83c0a33-922e-4a61-99b7-dc31bd14bf5a"),
                            MaSanPham = "SP3",
                            TenSanPham = "TSP3",
                            TrangThai = 1
                        },
                        new
                        {
                            IdSanPham = new Guid("1c5b395a-1eee-48e4-89e5-c39edee15b28"),
                            MaSanPham = "SP4",
                            TenSanPham = "TSP4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("SanPhamYeuThich");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7989650f-d673-4788-9549-2bd064534ddc"),
                            ChiTietSanPhamId = new Guid("615ff1b2-dcd2-4a85-a66e-3a75e3d4ee9f"),
                            NguoiDungId = new Guid("55d1353d-42be-4acb-a345-b920295d24dc"),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("c7150d2b-9791-40c8-902c-0fa3176babe7"),
                            ChiTietSanPhamId = new Guid("9fc49348-853b-4420-89bd-cf9b1e0bac6d"),
                            NguoiDungId = new Guid("a5a5b1fb-5ab6-49de-b376-9d6cfddc502f"),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("77ae0dc8-5b0f-48d9-b10a-d0be16cadfa9"),
                            ChiTietSanPhamId = new Guid("15787cc5-1116-4f68-aa0e-f591cdb1ef96"),
                            NguoiDungId = new Guid("a3383fbf-0883-4950-bb9f-87cb31040d44"),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("0a64ee5f-9bf1-4436-b165-1b7fa34d77e6"),
                            ChiTietSanPhamId = new Guid("1dfbf615-38e7-491e-b593-f59422a4bc06"),
                            NguoiDungId = new Guid("35172428-03d8-489d-ba34-a35534dcd22b"),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d20edc31-5fb0-47c2-aaea-35bee0999ae8"),
                            ChiTietSanPhamId = new Guid("d1e19dbe-8285-4ca7-b469-e67019a13aab"),
                            NguoiDungId = new Guid("abf2e001-7e62-42f8-b531-6c33b2d38a98"),
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ThongKe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Ngay")
                        .HasColumnType("int");

                    b.Property<Guid>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThongKe");
                });

            modelBuilder.Entity("Shop_Models.Entities.ThuongHieu", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("ThuongHieu");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("8f1cff3e-47cf-400b-a43e-acce4c031ab6"),
                            MaThuongHieu = "MTH0",
                            TenThuongHieu = "TTH0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("cb3f7283-8348-4553-8a9e-29e827b36329"),
                            MaThuongHieu = "MTH1",
                            TenThuongHieu = "TTH1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("b88bf1da-0b62-42b9-bb12-1376a602c077"),
                            MaThuongHieu = "MTH2",
                            TenThuongHieu = "TTH2",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("0f497143-dbd8-4a75-8554-cd8bbee260af"),
                            MaThuongHieu = "MTH3",
                            TenThuongHieu = "TTH3",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("7d3a3690-9963-440d-8369-2b9998564464"),
                            MaThuongHieu = "MTH4",
                            TenThuongHieu = "TTH4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Voucher");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4c8d9c2a-4aef-49d2-9cac-19fdc9c30f11"),
                            MaVoucher = "MVC0",
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8444),
                            NgayHetHan = new DateTime(2024, 6, 10, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8445),
                            PhanTramGiam = 86,
                            SoLuong = 3,
                            TenVoucher = "TVC0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("43ecde4d-0a46-45d1-ad86-68bf0d8fbc73"),
                            MaVoucher = "MVC1",
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8753),
                            NgayHetHan = new DateTime(2024, 6, 10, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8753),
                            PhanTramGiam = 88,
                            SoLuong = 7,
                            TenVoucher = "TVC1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("7e0cc6bf-1e19-48fc-bcf6-569d0ec6a826"),
                            MaVoucher = "MVC2",
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8941),
                            NgayHetHan = new DateTime(2024, 6, 12, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(8941),
                            PhanTramGiam = 56,
                            SoLuong = 3,
                            TenVoucher = "TVC2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("94091485-3714-497b-961c-67c925abad85"),
                            MaVoucher = "MVC3",
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9120),
                            NgayHetHan = new DateTime(2024, 5, 21, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9120),
                            PhanTramGiam = 68,
                            SoLuong = 3,
                            TenVoucher = "TVC3",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("cc82c5e1-cc7e-4043-a56a-67b5fcae9fc5"),
                            MaVoucher = "MVC4",
                            NgayBatDau = new DateTime(2024, 5, 16, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9363),
                            NgayHetHan = new DateTime(2024, 6, 5, 16, 34, 52, 687, DateTimeKind.Utc).AddTicks(9363),
                            PhanTramGiam = 45,
                            SoLuong = 1,
                            TenVoucher = "TVC4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.XuatXu", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaXuatXu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXuatXu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("XuatXu");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("3a8b5061-df10-413f-9882-cf7fcca75fc3"),
                            MaXuatXu = "MXX0",
                            TenXuatXu = "TXX0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("6e1d14fa-e4c5-419a-924b-6e14d2a1f519"),
                            MaXuatXu = "MXX1",
                            TenXuatXu = "TXX1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("4065adf3-e809-4d19-8613-a5fa5ab9e93c"),
                            MaXuatXu = "MXX2",
                            TenXuatXu = "TXX2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("388e582e-e112-487a-8f7e-0dea24ea7421"),
                            MaXuatXu = "MXX3",
                            TenXuatXu = "TXX3",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("5fa71732-6655-4df3-9da8-926be46b3c3b"),
                            MaXuatXu = "MXX4",
                            TenXuatXu = "TXX4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop_Models.Entities.Anh", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("Anhs")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany()
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.Khuyenmai", "Khuyenmai")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("Khuyenmai");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietSanPham", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChatLieu", "ChatLieu")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("ChatLieuId");

                    b.HasOne("Shop_Models.Entities.Loai", "Loai")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("LoaiId");

                    b.HasOne("Shop_Models.Entities.MauSac", "MauSac")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MauSacId");

                    b.HasOne("Shop_Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("SanPhamId");

                    b.HasOne("Shop_Models.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("ThuongHieuId");

                    b.HasOne("Shop_Models.Entities.XuatXu", "XuatXu")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("XuatXuId");

                    b.Navigation("ChatLieu");

                    b.Navigation("Loai");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("ThuongHieu");

                    b.Navigation("XuatXu");
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHang", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHangChiTiet", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDon", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.HasOne("Shop_Models.Entities.Voucher", "Vouchers")
                        .WithMany("HoaDon")
                        .HasForeignKey("VoucherId");

                    b.Navigation("NguoiDung");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucTTChiTiet", b =>
                {
                    b.HasOne("Shop_Models.Entities.HoaDon", "HoaDon")
                        .WithMany("PhuongThucTTChiTiet")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("PhuongThucTTChiTiets")
                        .HasForeignKey("PhuongThucThanhToanId");

                    b.Navigation("HoaDon");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPhamYeuThich", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("SanPhamYeuThich")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Shop_Models.Entities.ThongKe", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("ThongKes")
                        .HasForeignKey("ChiTietSanPhamId");

                    b.HasOne("Shop_Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ThongKes")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChatLieu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietSanPham", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("SanPhamYeuThich");

                    b.Navigation("ThongKes");
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDon", b =>
                {
                    b.Navigation("PhuongThucTTChiTiet");

                    b.Navigation("ThongKes");
                });

            modelBuilder.Entity("Shop_Models.Entities.Khuyenmai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("Shop_Models.Entities.Loai", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("PhuongThucTTChiTiets");
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.ThuongHieu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.Voucher", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Shop_Models.Entities.XuatXu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
