// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Api.AppDbContext;

#nullable disable

namespace Shop_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240517053649_gendata2")]
    partial class gendata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shop_Models.Dto.SanPhamYeuThichViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<double?>("GiaThucTe")
                        .HasColumnType("float");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPhamCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiCTSP")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiND")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VerificationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SanPhamYeuThichViewModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25686649-a331-4070-a790-8a90adb18c2b"),
                            AnhSanPham = "URL0",
                            ChiTietSanPhamId = new Guid("b595661d-0ac3-4bd6-9f95-79bf8422156e"),
                            DiaChi = "DC0",
                            GiaBan = 458474.0,
                            GiaNhap = 575753.0,
                            GiaThucTe = 495289.0,
                            GioiTinh = true,
                            MaAnh = "MA0",
                            MaNguoiDung = "ND0",
                            MaSanPham = "MSP0",
                            MaSanPhamCT = "MSPCT0",
                            Mota = "mo ta0",
                            SoDienThoai = "Null0",
                            SoLuongDaBan = 0,
                            SoLuongTon = 0,
                            TenNguoiDung = "TND0",
                            TenSanPham = "TSP0",
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 1,
                            TrangThaiND = 0,
                            URL = "URL0",
                            VerificationCode = "VC0",
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("052de339-0e52-444b-8768-5978cafcba4c"),
                            AnhSanPham = "URL1",
                            ChiTietSanPhamId = new Guid("7fd021bb-27c4-485c-af09-c3ae8ad334c3"),
                            DiaChi = "DC1",
                            GiaBan = 197556.0,
                            GiaNhap = 161885.0,
                            GiaThucTe = 230893.0,
                            GioiTinh = true,
                            MaAnh = "MA1",
                            MaNguoiDung = "ND1",
                            MaSanPham = "MSP1",
                            MaSanPhamCT = "MSPCT1",
                            Mota = "mo ta1",
                            SoDienThoai = "Null1",
                            SoLuongDaBan = 1,
                            SoLuongTon = 1,
                            TenNguoiDung = "TND1",
                            TenSanPham = "TSP1",
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 1,
                            TrangThaiND = 0,
                            URL = "URL1",
                            VerificationCode = "VC1",
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a6b8d879-94e9-4a87-80ce-538df534c1af"),
                            AnhSanPham = "URL2",
                            ChiTietSanPhamId = new Guid("63542b47-aed4-4767-a3dd-e0cbcf9dbca0"),
                            DiaChi = "DC2",
                            GiaBan = 515608.0,
                            GiaNhap = 429939.0,
                            GiaThucTe = 384974.0,
                            GioiTinh = true,
                            MaAnh = "MA2",
                            MaNguoiDung = "ND2",
                            MaSanPham = "MSP2",
                            MaSanPhamCT = "MSPCT2",
                            Mota = "mo ta2",
                            SoDienThoai = "Null2",
                            SoLuongDaBan = 2,
                            SoLuongTon = 2,
                            TenNguoiDung = "TND2",
                            TenSanPham = "TSP2",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 1,
                            TrangThaiND = 0,
                            URL = "URL2",
                            VerificationCode = "VC2",
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("38675b55-15fe-4221-977e-fa847fc0c114"),
                            AnhSanPham = "URL3",
                            ChiTietSanPhamId = new Guid("172083dd-a38c-47df-b233-41cb995762f3"),
                            DiaChi = "DC3",
                            GiaBan = 808873.0,
                            GiaNhap = 269676.0,
                            GiaThucTe = 673670.0,
                            GioiTinh = true,
                            MaAnh = "MA3",
                            MaNguoiDung = "ND3",
                            MaSanPham = "MSP3",
                            MaSanPhamCT = "MSPCT3",
                            Mota = "mo ta3",
                            SoDienThoai = "Null3",
                            SoLuongDaBan = 3,
                            SoLuongTon = 3,
                            TenNguoiDung = "TND3",
                            TenSanPham = "TSP3",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            URL = "URL3",
                            VerificationCode = "VC3",
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4a404681-a5ef-4a0d-b72c-1e9ae5925e1c"),
                            AnhSanPham = "URL4",
                            ChiTietSanPhamId = new Guid("f2345383-874c-412e-b402-0d6b4d8997f9"),
                            DiaChi = "DC4",
                            GiaBan = 359599.0,
                            GiaNhap = 510540.0,
                            GiaThucTe = 894492.0,
                            GioiTinh = true,
                            MaAnh = "MA4",
                            MaNguoiDung = "ND4",
                            MaSanPham = "MSP4",
                            MaSanPhamCT = "MSPCT4",
                            Mota = "mo ta4",
                            SoDienThoai = "Null4",
                            SoLuongDaBan = 4,
                            SoLuongTon = 4,
                            TenNguoiDung = "TND4",
                            TenSanPham = "TSP4",
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            TrangThaiND = 0,
                            URL = "URL4",
                            VerificationCode = "VC4",
                            VerificationCodeExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Anh", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.HasIndex("ChiTietSanPhamId");

                    b.ToTable("Anh");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("d70bea03-0ef6-43c0-8f2f-d1e0430640e7"),
                            ChiTietSanPhamId = new Guid("b595661d-0ac3-4bd6-9f95-79bf8422156e"),
                            MaAnh = "MA0",
                            URL = "URL0"
                        },
                        new
                        {
                            Guid = new Guid("525cf895-0bc9-4f77-b285-4f7d2190a647"),
                            ChiTietSanPhamId = new Guid("7fd021bb-27c4-485c-af09-c3ae8ad334c3"),
                            MaAnh = "MA1",
                            URL = "URL1"
                        },
                        new
                        {
                            Guid = new Guid("d9bff799-948b-4642-a1a4-0ec84ddbd8f1"),
                            ChiTietSanPhamId = new Guid("63542b47-aed4-4767-a3dd-e0cbcf9dbca0"),
                            MaAnh = "MA2",
                            URL = "URL2"
                        },
                        new
                        {
                            Guid = new Guid("c2a2e4d6-c091-4d93-bdcb-3c427e4442ab"),
                            ChiTietSanPhamId = new Guid("172083dd-a38c-47df-b233-41cb995762f3"),
                            MaAnh = "MA3",
                            URL = "URL3"
                        },
                        new
                        {
                            Guid = new Guid("dd610c25-e3e5-4748-8178-13fa2cb60712"),
                            ChiTietSanPhamId = new Guid("f2345383-874c-412e-b402-0d6b4d8997f9"),
                            MaAnh = "MA4",
                            URL = "URL4"
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChatLieu", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChatLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("ChatLieu");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("3ffb61bf-42bf-4e42-b1e6-52cdfeb604ad"),
                            MaChatLieu = "MCL0",
                            TenChatLieu = "TCL0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("6b6b6101-17d7-45d1-b422-cd5646ce89a3"),
                            MaChatLieu = "MCL1",
                            TenChatLieu = "TCL1",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("0e5b251e-1667-426d-8844-e673cfddf173"),
                            MaChatLieu = "MCL2",
                            TenChatLieu = "TCL2",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("320172fc-9d5c-408d-b277-ea9129accd30"),
                            MaChatLieu = "MCL3",
                            TenChatLieu = "TCL3",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("517b06fd-802a-467d-8d21-052172695a95"),
                            MaChatLieu = "MCL4",
                            TenChatLieu = "TCL4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietKhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhuyenMaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("KhuyenMaiId");

                    b.ToTable("ChiTietKhuyenMai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75ecd1bf-5b60-4e77-84f4-a2195b4385ec"),
                            ChiTietSanPhamId = new Guid("b595661d-0ac3-4bd6-9f95-79bf8422156e"),
                            KhuyenMaiId = new Guid("f4fd95d3-cd37-4243-a339-58196e0c7708"),
                            Mota = "MTCTKM0",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d436a7ef-0719-40e3-a08c-c20cda6b1862"),
                            ChiTietSanPhamId = new Guid("7fd021bb-27c4-485c-af09-c3ae8ad334c3"),
                            KhuyenMaiId = new Guid("a199fa94-0315-4bf9-b0b7-a5e048726c93"),
                            Mota = "MTCTKM1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("412eb1e9-6587-491a-92a7-de1d6d305d2f"),
                            ChiTietSanPhamId = new Guid("63542b47-aed4-4767-a3dd-e0cbcf9dbca0"),
                            KhuyenMaiId = new Guid("5946c004-510e-48f0-b3e9-165951dc9796"),
                            Mota = "MTCTKM2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("379bc528-fae5-4433-8451-be3571849d86"),
                            ChiTietSanPhamId = new Guid("172083dd-a38c-47df-b233-41cb995762f3"),
                            KhuyenMaiId = new Guid("68b0507c-9acb-4243-b592-3d2019ed9098"),
                            Mota = "MTCTKM3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("6407fd61-e480-4990-aa4d-1b4fad410b60"),
                            ChiTietSanPhamId = new Guid("f2345383-874c-412e-b402-0d6b4d8997f9"),
                            KhuyenMaiId = new Guid("7f3d4005-0b1c-421f-8a0a-7c87320fb43f"),
                            Mota = "MTCTKM4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<double?>("GiaThucTe")
                        .HasColumnType("float");

                    b.Property<Guid?>("LoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MauSacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<Guid?>("ThuongHieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<Guid?>("XuatXuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatLieuId");

                    b.HasIndex("LoaiId");

                    b.HasIndex("MauSacId");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("ThuongHieuId");

                    b.HasIndex("XuatXuId");

                    b.ToTable("ChiTietSanPham");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b595661d-0ac3-4bd6-9f95-79bf8422156e"),
                            ChatLieuId = new Guid("3ffb61bf-42bf-4e42-b1e6-52cdfeb604ad"),
                            GiaBan = 899216.0,
                            GiaNhap = 463901.0,
                            GiaThucTe = 321305.0,
                            LoaiId = new Guid("9eb2060e-d5f2-4282-b64c-beeca4cd4bbf"),
                            MaSanPham = "SP0",
                            MauSacId = new Guid("72e1837d-7aa5-4049-b670-a309f9f7c759"),
                            Mota = "mo ta0",
                            SanPhamId = new Guid("464b595a-e411-46b9-a8aa-c242b7481630"),
                            SoLuongDaBan = 0,
                            SoLuongTon = 0,
                            ThuongHieuId = new Guid("1fdadddf-95ec-4bf5-a18d-bda995484da3"),
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 0,
                            XuatXuId = new Guid("5a5dc823-7dd2-4f30-9206-abf854bb8e0e")
                        },
                        new
                        {
                            Id = new Guid("7fd021bb-27c4-485c-af09-c3ae8ad334c3"),
                            ChatLieuId = new Guid("6b6b6101-17d7-45d1-b422-cd5646ce89a3"),
                            GiaBan = 369383.0,
                            GiaNhap = 578199.0,
                            GiaThucTe = 565485.0,
                            LoaiId = new Guid("2c19a79c-e9cf-4f6b-8e76-af237b00eadb"),
                            MaSanPham = "SP1",
                            MauSacId = new Guid("db0e2d0d-9e90-499e-8aaf-4f87d47c2cd9"),
                            Mota = "mo ta1",
                            SanPhamId = new Guid("b65d38ad-7d66-4724-bd54-81b82cd673b1"),
                            SoLuongDaBan = 1,
                            SoLuongTon = 1,
                            ThuongHieuId = new Guid("065b545f-96b2-4933-b23b-c29f1c3c9fe5"),
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 1,
                            XuatXuId = new Guid("f02fb681-eb7b-4c59-8370-82d474dfb0bf")
                        },
                        new
                        {
                            Id = new Guid("63542b47-aed4-4767-a3dd-e0cbcf9dbca0"),
                            ChatLieuId = new Guid("0e5b251e-1667-426d-8844-e673cfddf173"),
                            GiaBan = 693669.0,
                            GiaNhap = 496536.0,
                            GiaThucTe = 855208.0,
                            LoaiId = new Guid("e6fe15eb-d6d1-49ee-9037-772c80609a19"),
                            MaSanPham = "SP2",
                            MauSacId = new Guid("93b35b0e-03f4-4204-b1ea-7d949559c4f4"),
                            Mota = "mo ta2",
                            SanPhamId = new Guid("0424aa20-dffd-428b-b9c5-c63e8b9ca76f"),
                            SoLuongDaBan = 2,
                            SoLuongTon = 2,
                            ThuongHieuId = new Guid("bb78da4e-3c7b-4e4f-b520-6e1422a01748"),
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            XuatXuId = new Guid("865a66da-aced-494d-b042-bb8460ed5c4a")
                        },
                        new
                        {
                            Id = new Guid("172083dd-a38c-47df-b233-41cb995762f3"),
                            ChatLieuId = new Guid("320172fc-9d5c-408d-b277-ea9129accd30"),
                            GiaBan = 449686.0,
                            GiaNhap = 910676.0,
                            GiaThucTe = 915513.0,
                            LoaiId = new Guid("47d036de-3761-4bb8-93b2-db4d7c9c462e"),
                            MaSanPham = "SP3",
                            MauSacId = new Guid("ca787e5a-67ee-4677-9343-f33daa04d083"),
                            Mota = "mo ta3",
                            SanPhamId = new Guid("90fe4a91-3411-4b04-b083-2d165bf11621"),
                            SoLuongDaBan = 3,
                            SoLuongTon = 3,
                            ThuongHieuId = new Guid("caba8296-af36-4ace-8eff-b8a95793dc16"),
                            TrangThai = 1,
                            TrangThaiKhuyenMai = 0,
                            XuatXuId = new Guid("917c5195-7023-403d-ba27-ea525b1d6773")
                        },
                        new
                        {
                            Id = new Guid("f2345383-874c-412e-b402-0d6b4d8997f9"),
                            ChatLieuId = new Guid("517b06fd-802a-467d-8d21-052172695a95"),
                            GiaBan = 594524.0,
                            GiaNhap = 309629.0,
                            GiaThucTe = 607321.0,
                            LoaiId = new Guid("247acb69-633d-4854-b957-cd53340a81f0"),
                            MaSanPham = "SP4",
                            MauSacId = new Guid("aa5c4170-e9ab-458d-b8b6-a65d5bf13aba"),
                            Mota = "mo ta4",
                            SanPhamId = new Guid("c6d356c6-6226-4524-973d-47eac50ca855"),
                            SoLuongDaBan = 4,
                            SoLuongTon = 4,
                            ThuongHieuId = new Guid("3850a3f0-0c54-4bff-acce-43da894ab287"),
                            TrangThai = 0,
                            TrangThaiKhuyenMai = 0,
                            XuatXuId = new Guid("c2d2faff-bbf2-4f66-a964-c5aa35060db3")
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHang", b =>
                {
                    b.Property<Guid>("IdGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdGh");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("GioHang");

                    b.HasData(
                        new
                        {
                            IdGh = new Guid("e234d1b6-80c5-44df-a1f9-516c86f9e00a"),
                            IdNguoiDung = new Guid("3c13d1fd-b769-4810-b907-e678c90f8d74"),
                            TrangThai = 0
                        },
                        new
                        {
                            IdGh = new Guid("1ba920b0-28db-4cfa-98c2-e00be9bc856b"),
                            IdNguoiDung = new Guid("cf9d63bd-1722-41c4-8480-29c8e2d476b7"),
                            TrangThai = 1
                        },
                        new
                        {
                            IdGh = new Guid("a08116ab-fb9b-4254-a812-40e6eb651ee6"),
                            IdNguoiDung = new Guid("ea017396-34f4-4e42-805a-881830bbcc7b"),
                            TrangThai = 1
                        },
                        new
                        {
                            IdGh = new Guid("15038afa-f010-425d-98b0-e1c034bc3209"),
                            IdNguoiDung = new Guid("4fc5d1ed-9782-496c-b54e-3e000554bd74"),
                            TrangThai = 0
                        },
                        new
                        {
                            IdGh = new Guid("71fb2077-4ad9-4be3-a0b0-a045be178af7"),
                            IdNguoiDung = new Guid("3bfc8ff2-7257-4661-ac08-e50bf3b35e74"),
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double>("GiaGoc")
                        .HasColumnType("float");

                    b.Property<Guid>("GioHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("GioHangId");

                    b.ToTable("GioHangChiTiet");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiDoHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayShip")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double>("TienShip")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<int>("TrangThaiGiaoHang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("VoucherId");

                    b.ToTable("HoaDon");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7edbeed0-8949-4d25-bf38-5e0ebd68b977"),
                            LiDoHuy = "ly do huy0",
                            MaHoaDon = "HD0",
                            MoTa = "mo ta0",
                            NgayGiaoDuKien = new DateTime(2024, 5, 28, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3720),
                            NgayNhan = new DateTime(2024, 5, 28, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3717),
                            NgayShip = new DateTime(2024, 5, 22, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3717),
                            NgayTao = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3715),
                            NgayThanhToan = new DateTime(2024, 5, 23, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3716),
                            TienGiam = 15355.0,
                            TienShip = 12744.0,
                            TongTien = 552789.0,
                            TrangThaiGiaoHang = 1,
                            TrangThaiThanhToan = 0
                        },
                        new
                        {
                            Id = new Guid("85099f01-53a2-4036-af93-4acbd14f5b7d"),
                            LiDoHuy = "ly do huy1",
                            MaHoaDon = "HD1",
                            MoTa = "mo ta1",
                            NgayGiaoDuKien = new DateTime(2024, 5, 26, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4097),
                            NgayNhan = new DateTime(2024, 5, 24, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4096),
                            NgayShip = new DateTime(2024, 5, 22, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4095),
                            NgayTao = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4095),
                            NgayThanhToan = new DateTime(2024, 5, 20, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4095),
                            TienGiam = 54738.0,
                            TienShip = 43566.0,
                            TongTien = 621099.0,
                            TrangThaiGiaoHang = 1,
                            TrangThaiThanhToan = 0
                        },
                        new
                        {
                            Id = new Guid("6fb3cf44-f12d-49e4-aa5d-944fd4800d47"),
                            LiDoHuy = "ly do huy2",
                            MaHoaDon = "HD2",
                            MoTa = "mo ta2",
                            NgayGiaoDuKien = new DateTime(2024, 5, 29, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4295),
                            NgayNhan = new DateTime(2024, 5, 24, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4293),
                            NgayShip = new DateTime(2024, 5, 20, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4292),
                            NgayTao = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4291),
                            NgayThanhToan = new DateTime(2024, 5, 19, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4292),
                            TienGiam = 66522.0,
                            TienShip = 38434.0,
                            TongTien = 865571.0,
                            TrangThaiGiaoHang = 0,
                            TrangThaiThanhToan = 1
                        },
                        new
                        {
                            Id = new Guid("6c16c585-8658-4651-8df7-0f7050aef4c9"),
                            LiDoHuy = "ly do huy3",
                            MaHoaDon = "HD3",
                            MoTa = "mo ta3",
                            NgayGiaoDuKien = new DateTime(2024, 5, 30, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4526),
                            NgayNhan = new DateTime(2024, 5, 26, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4525),
                            NgayShip = new DateTime(2024, 5, 22, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4524),
                            NgayTao = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4523),
                            NgayThanhToan = new DateTime(2024, 5, 18, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4524),
                            TienGiam = 33968.0,
                            TienShip = 20416.0,
                            TongTien = 424769.0,
                            TrangThaiGiaoHang = 1,
                            TrangThaiThanhToan = 1
                        },
                        new
                        {
                            Id = new Guid("699ac7cb-9655-499a-9cbb-e7d59290613d"),
                            LiDoHuy = "ly do huy4",
                            MaHoaDon = "HD4",
                            MoTa = "mo ta4",
                            NgayGiaoDuKien = new DateTime(2024, 5, 25, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4778),
                            NgayNhan = new DateTime(2024, 5, 26, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4776),
                            NgayShip = new DateTime(2024, 5, 20, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4775),
                            NgayTao = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4774),
                            NgayThanhToan = new DateTime(2024, 5, 18, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4775),
                            TienGiam = 76207.0,
                            TienShip = 42788.0,
                            TongTien = 241329.0,
                            TrangThaiGiaoHang = 1,
                            TrangThaiThanhToan = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("HoaDonChiTiet");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4b79433b-157a-4e96-bc25-25490a6daf09"),
                            ChiTietSanPhamId = new Guid("b595661d-0ac3-4bd6-9f95-79bf8422156e"),
                            GiaBan = 952757.0,
                            HoaDonId = new Guid("7edbeed0-8949-4d25-bf38-5e0ebd68b977"),
                            SoLuong = 60
                        },
                        new
                        {
                            Guid = new Guid("69b4b984-8483-4213-8fe1-634ef897a70c"),
                            ChiTietSanPhamId = new Guid("7fd021bb-27c4-485c-af09-c3ae8ad334c3"),
                            GiaBan = 489928.0,
                            HoaDonId = new Guid("85099f01-53a2-4036-af93-4acbd14f5b7d"),
                            SoLuong = 14
                        },
                        new
                        {
                            Guid = new Guid("b174414b-01aa-44fe-951b-04f661573a1e"),
                            ChiTietSanPhamId = new Guid("63542b47-aed4-4767-a3dd-e0cbcf9dbca0"),
                            GiaBan = 249931.0,
                            HoaDonId = new Guid("6fb3cf44-f12d-49e4-aa5d-944fd4800d47"),
                            SoLuong = 12
                        },
                        new
                        {
                            Guid = new Guid("4b010b8a-c55f-4fed-a25f-515bd695a5ff"),
                            ChiTietSanPhamId = new Guid("172083dd-a38c-47df-b233-41cb995762f3"),
                            GiaBan = 402751.0,
                            HoaDonId = new Guid("6c16c585-8658-4651-8df7-0f7050aef4c9"),
                            SoLuong = 50
                        },
                        new
                        {
                            Guid = new Guid("8917becd-df33-487c-8391-bbf00c775d50"),
                            ChiTietSanPhamId = new Guid("f2345383-874c-412e-b402-0d6b4d8997f9"),
                            GiaBan = 138018.0,
                            HoaDonId = new Guid("699ac7cb-9655-499a-9cbb-e7d59290613d"),
                            SoLuong = 20
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Khuyenmai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiHinhKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MucGiam")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Khuyenmai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4fd95d3-cd37-4243-a339-58196e0c7708"),
                            LoaiHinhKhuyenMai = "LHKM0",
                            MaKhuyenMai = "MKM0",
                            MucGiam = 74.0,
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3614),
                            NgayKetThuc = new DateTime(2024, 5, 26, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3617),
                            TenKhuyenMai = "TKM0",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("a199fa94-0315-4bf9-b0b7-a5e048726c93"),
                            LoaiHinhKhuyenMai = "LHKM1",
                            MaKhuyenMai = "MKM1",
                            MucGiam = 76.0,
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4056),
                            NgayKetThuc = new DateTime(2024, 6, 6, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4056),
                            TenKhuyenMai = "TKM1",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("5946c004-510e-48f0-b3e9-165951dc9796"),
                            LoaiHinhKhuyenMai = "LHKM2",
                            MaKhuyenMai = "MKM2",
                            MucGiam = 35.0,
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4257),
                            NgayKetThuc = new DateTime(2024, 5, 18, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4258),
                            TenKhuyenMai = "TKM2",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("68b0507c-9acb-4243-b592-3d2019ed9098"),
                            LoaiHinhKhuyenMai = "LHKM3",
                            MaKhuyenMai = "MKM3",
                            MucGiam = 61.0,
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4491),
                            NgayKetThuc = new DateTime(2024, 6, 12, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4491),
                            TenKhuyenMai = "TKM3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("7f3d4005-0b1c-421f-8a0a-7c87320fb43f"),
                            LoaiHinhKhuyenMai = "LHKM4",
                            MaKhuyenMai = "MKM4",
                            MucGiam = 22.0,
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4704),
                            NgayKetThuc = new DateTime(2024, 6, 5, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4705),
                            TenKhuyenMai = "TKM4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Loai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9eb2060e-d5f2-4282-b64c-beeca4cd4bbf"),
                            MaLoai = "ML0",
                            TenLoai = "TL0",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("2c19a79c-e9cf-4f6b-8e76-af237b00eadb"),
                            MaLoai = "ML1",
                            TenLoai = "TL1",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("e6fe15eb-d6d1-49ee-9037-772c80609a19"),
                            MaLoai = "ML2",
                            TenLoai = "TL2",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("47d036de-3761-4bb8-93b2-db4d7c9c462e"),
                            MaLoai = "ML3",
                            TenLoai = "TL3",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("247acb69-633d-4854-b957-cd53340a81f0"),
                            MaLoai = "ML4",
                            TenLoai = "TL4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("72e1837d-7aa5-4049-b670-a309f9f7c759"),
                            MaMauSac = "MMS0",
                            TenMauSac = "TMS0",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("db0e2d0d-9e90-499e-8aaf-4f87d47c2cd9"),
                            MaMauSac = "MMS1",
                            TenMauSac = "TMS1",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("93b35b0e-03f4-4204-b1ea-7d949559c4f4"),
                            MaMauSac = "MMS2",
                            TenMauSac = "TMS2",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("ca787e5a-67ee-4677-9343-f33daa04d083"),
                            MaMauSac = "MMS3",
                            TenMauSac = "TMS3",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("aa5c4170-e9ab-458d-b8b6-a65d5bf13aba"),
                            MaMauSac = "MMS4",
                            TenMauSac = "TMS4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VerificationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c13d1fd-b769-4810-b907-e678c90f8d74"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f53f1e72-9e31-4734-9cf5-6a5aa2d8018a",
                            DiaChi = "DC0",
                            EmailConfirmed = false,
                            GioiTinh = true,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND0",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null0",
                            TenNguoiDung = "TND0",
                            TrangThai = 0,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC0",
                            VerificationCodeExpiry = new DateTime(2024, 5, 17, 12, 36, 48, 533, DateTimeKind.Utc).AddTicks(3685)
                        },
                        new
                        {
                            Id = new Guid("cf9d63bd-1722-41c4-8480-29c8e2d476b7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3bd7ee5f-434a-4c6b-b05f-325cb81c3840",
                            DiaChi = "DC1",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND1",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null1",
                            TenNguoiDung = "TND1",
                            TrangThai = 0,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC1",
                            VerificationCodeExpiry = new DateTime(2024, 5, 17, 22, 36, 48, 533, DateTimeKind.Utc).AddTicks(4079)
                        },
                        new
                        {
                            Id = new Guid("ea017396-34f4-4e42-805a-881830bbcc7b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e27ba02a-2872-4aee-af26-edb01b544c0c",
                            DiaChi = "DC2",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND2",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null2",
                            TenNguoiDung = "TND2",
                            TrangThai = 0,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC2",
                            VerificationCodeExpiry = new DateTime(2024, 5, 17, 14, 36, 48, 533, DateTimeKind.Utc).AddTicks(4278)
                        },
                        new
                        {
                            Id = new Guid("4fc5d1ed-9782-496c-b54e-3e000554bd74"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba798b21-9e7d-49b8-aef8-95ef34369dc2",
                            DiaChi = "DC3",
                            EmailConfirmed = false,
                            GioiTinh = true,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND3",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null3",
                            TenNguoiDung = "TND3",
                            TrangThai = 0,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC3",
                            VerificationCodeExpiry = new DateTime(2024, 5, 17, 21, 36, 48, 533, DateTimeKind.Utc).AddTicks(4510)
                        },
                        new
                        {
                            Id = new Guid("3bfc8ff2-7257-4661-ac08-e50bf3b35e74"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a25bad70-7891-4430-863b-1c7ad7d4afe2",
                            DiaChi = "DC4",
                            EmailConfirmed = false,
                            GioiTinh = false,
                            LockoutEnabled = false,
                            MaNguoiDung = "ND4",
                            PhoneNumberConfirmed = false,
                            SoDienThoai = "Null4",
                            TenNguoiDung = "TND4",
                            TrangThai = 1,
                            TwoFactorEnabled = false,
                            VerificationCode = "VC4",
                            VerificationCodeExpiry = new DateTime(2024, 5, 17, 10, 36, 48, 533, DateTimeKind.Utc).AddTicks(4728)
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMaPTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43c06cfa-db5f-476a-b4ee-59f5b48d8dc6"),
                            MaPTThanhToan = "MPTTT0",
                            MoTa = "MTPTTT0",
                            TenMaPTThanhToan = "TPTTT0",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("f483de02-af61-4dd4-9564-09b001e70dfd"),
                            MaPTThanhToan = "MPTTT1",
                            MoTa = "MTPTTT1",
                            TenMaPTThanhToan = "TPTTT1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("20720683-298c-46c5-a9cd-8a4164abf9df"),
                            MaPTThanhToan = "MPTTT2",
                            MoTa = "MTPTTT2",
                            TenMaPTThanhToan = "TPTTT2",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("23eb3b12-1de2-4a40-8735-58350e70c9ec"),
                            MaPTThanhToan = "MPTTT3",
                            MoTa = "MTPTTT3",
                            TenMaPTThanhToan = "TPTTT3",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("948fdaf0-b45e-4054-b1c7-3881729bc7f2"),
                            MaPTThanhToan = "MPTTT4",
                            MoTa = "MTPTTT4",
                            TenMaPTThanhToan = "TPTTT4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucTTChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PTTToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhuongThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SoTien")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("PhuongThucTTChiTiet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2489432b-be5a-409f-ab5d-6bbec4708734"),
                            HoaDonId = new Guid("7edbeed0-8949-4d25-bf38-5e0ebd68b977"),
                            PTTToanId = new Guid("43c06cfa-db5f-476a-b4ee-59f5b48d8dc6"),
                            SoTien = 280325.0,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("f1b6d503-23ed-46d7-bd3c-27c94b6905f6"),
                            HoaDonId = new Guid("85099f01-53a2-4036-af93-4acbd14f5b7d"),
                            PTTToanId = new Guid("f483de02-af61-4dd4-9564-09b001e70dfd"),
                            SoTien = 513038.0,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("984db239-7caf-4ef2-995b-b285991ef80e"),
                            HoaDonId = new Guid("6fb3cf44-f12d-49e4-aa5d-944fd4800d47"),
                            PTTToanId = new Guid("20720683-298c-46c5-a9cd-8a4164abf9df"),
                            SoTien = 480057.0,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("0ae642f3-5fc1-4e02-927d-8099d26e1236"),
                            HoaDonId = new Guid("6c16c585-8658-4651-8df7-0f7050aef4c9"),
                            PTTToanId = new Guid("23eb3b12-1de2-4a40-8735-58350e70c9ec"),
                            SoTien = 250963.0,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ee389885-67f0-46fa-952c-69a628d0e294"),
                            HoaDonId = new Guid("699ac7cb-9655-499a-9cbb-e7d59290613d"),
                            PTTToanId = new Guid("948fdaf0-b45e-4054-b1c7-3881729bc7f2"),
                            SoTien = 191449.0,
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdSanPham");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            IdSanPham = new Guid("464b595a-e411-46b9-a8aa-c242b7481630"),
                            MaSanPham = "SP0",
                            TenSanPham = "TSP0",
                            TrangThai = 1
                        },
                        new
                        {
                            IdSanPham = new Guid("b65d38ad-7d66-4724-bd54-81b82cd673b1"),
                            MaSanPham = "SP1",
                            TenSanPham = "TSP1",
                            TrangThai = 0
                        },
                        new
                        {
                            IdSanPham = new Guid("0424aa20-dffd-428b-b9c5-c63e8b9ca76f"),
                            MaSanPham = "SP2",
                            TenSanPham = "TSP2",
                            TrangThai = 1
                        },
                        new
                        {
                            IdSanPham = new Guid("90fe4a91-3411-4b04-b083-2d165bf11621"),
                            MaSanPham = "SP3",
                            TenSanPham = "TSP3",
                            TrangThai = 1
                        },
                        new
                        {
                            IdSanPham = new Guid("c6d356c6-6226-4524-973d-47eac50ca855"),
                            MaSanPham = "SP4",
                            TenSanPham = "TSP4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("SanPhamYeuThich");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8eea5275-1919-4a8c-813e-13d27f1911f3"),
                            ChiTietSanPhamId = new Guid("b595661d-0ac3-4bd6-9f95-79bf8422156e"),
                            NguoiDungId = new Guid("3c13d1fd-b769-4810-b907-e678c90f8d74"),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("35f146a6-3fe0-4cf5-adb7-9b10ff614f81"),
                            ChiTietSanPhamId = new Guid("7fd021bb-27c4-485c-af09-c3ae8ad334c3"),
                            NguoiDungId = new Guid("cf9d63bd-1722-41c4-8480-29c8e2d476b7"),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("212dbc20-0b78-4c31-9741-d1f2f24e9468"),
                            ChiTietSanPhamId = new Guid("63542b47-aed4-4767-a3dd-e0cbcf9dbca0"),
                            NguoiDungId = new Guid("ea017396-34f4-4e42-805a-881830bbcc7b"),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("33f8a3ab-1428-4170-81b0-e6b981b109f1"),
                            ChiTietSanPhamId = new Guid("172083dd-a38c-47df-b233-41cb995762f3"),
                            NguoiDungId = new Guid("4fc5d1ed-9782-496c-b54e-3e000554bd74"),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = new Guid("df5d8a16-2f12-4974-8cbb-1a980bd4a863"),
                            ChiTietSanPhamId = new Guid("f2345383-874c-412e-b402-0d6b4d8997f9"),
                            NguoiDungId = new Guid("3bfc8ff2-7257-4661-ac08-e50bf3b35e74"),
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.ThongKe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiTietSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Ngay")
                        .HasColumnType("int");

                    b.Property<Guid>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietSanPhamId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThongKe");
                });

            modelBuilder.Entity("Shop_Models.Entities.ThuongHieu", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("ThuongHieu");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("1fdadddf-95ec-4bf5-a18d-bda995484da3"),
                            MaThuongHieu = "MTH0",
                            TenThuongHieu = "TTH0",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("065b545f-96b2-4933-b23b-c29f1c3c9fe5"),
                            MaThuongHieu = "MTH1",
                            TenThuongHieu = "TTH1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("bb78da4e-3c7b-4e4f-b520-6e1422a01748"),
                            MaThuongHieu = "MTH2",
                            TenThuongHieu = "TTH2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("caba8296-af36-4ace-8eff-b8a95793dc16"),
                            MaThuongHieu = "MTH3",
                            TenThuongHieu = "TTH3",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("3850a3f0-0c54-4bff-acce-43da894ab287"),
                            MaThuongHieu = "MTH4",
                            TenThuongHieu = "TTH4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Voucher");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4d215531-a037-4e97-8b97-77c9cf533af7"),
                            MaVoucher = "MVC0",
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3809),
                            NgayHetHan = new DateTime(2024, 5, 28, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(3809),
                            PhanTramGiam = 89,
                            SoLuong = 4,
                            TenVoucher = "TVC0",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("b1226b65-63a1-47bb-9504-03b273e75817"),
                            MaVoucher = "MVC1",
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4141),
                            NgayHetHan = new DateTime(2024, 5, 28, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4141),
                            PhanTramGiam = 37,
                            SoLuong = 6,
                            TenVoucher = "TVC1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("b216a082-202f-4550-a4d0-0b444f82bd88"),
                            MaVoucher = "MVC2",
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4305),
                            NgayHetHan = new DateTime(2024, 5, 31, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4305),
                            PhanTramGiam = 70,
                            SoLuong = 5,
                            TenVoucher = "TVC2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("d821622e-61b8-49a0-a652-faa83283e8f7"),
                            MaVoucher = "MVC3",
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4537),
                            NgayHetHan = new DateTime(2024, 5, 28, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4537),
                            PhanTramGiam = 36,
                            SoLuong = 0,
                            TenVoucher = "TVC3",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("c95087f8-de66-488f-ad72-7f77c85de422"),
                            MaVoucher = "MVC4",
                            NgayBatDau = new DateTime(2024, 5, 17, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4794),
                            NgayHetHan = new DateTime(2024, 5, 18, 5, 36, 48, 533, DateTimeKind.Utc).AddTicks(4795),
                            PhanTramGiam = 59,
                            SoLuong = 9,
                            TenVoucher = "TVC4",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("Shop_Models.Entities.XuatXu", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaXuatXu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXuatXu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("XuatXu");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("5a5dc823-7dd2-4f30-9206-abf854bb8e0e"),
                            MaXuatXu = "MXX0",
                            TenXuatXu = "TXX0",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("f02fb681-eb7b-4c59-8370-82d474dfb0bf"),
                            MaXuatXu = "MXX1",
                            TenXuatXu = "TXX1",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("865a66da-aced-494d-b042-bb8460ed5c4a"),
                            MaXuatXu = "MXX2",
                            TenXuatXu = "TXX2",
                            TrangThai = 1
                        },
                        new
                        {
                            Guid = new Guid("917c5195-7023-403d-ba27-ea525b1d6773"),
                            MaXuatXu = "MXX3",
                            TenXuatXu = "TXX3",
                            TrangThai = 0
                        },
                        new
                        {
                            Guid = new Guid("c2d2faff-bbf2-4f66-a964-c5aa35060db3"),
                            MaXuatXu = "MXX4",
                            TenXuatXu = "TXX4",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop_Models.Entities.Anh", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("Anhs")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany()
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.Khuyenmai", "Khuyenmai")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("Khuyenmai");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietSanPham", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChatLieu", "ChatLieu")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("ChatLieuId");

                    b.HasOne("Shop_Models.Entities.Loai", "Loai")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("LoaiId");

                    b.HasOne("Shop_Models.Entities.MauSac", "MauSac")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MauSacId");

                    b.HasOne("Shop_Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("SanPhamId");

                    b.HasOne("Shop_Models.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("ThuongHieuId");

                    b.HasOne("Shop_Models.Entities.XuatXu", "XuatXu")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("XuatXuId");

                    b.Navigation("ChatLieu");

                    b.Navigation("Loai");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("ThuongHieu");

                    b.Navigation("XuatXu");
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHang", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHangChiTiet", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDon", b =>
                {
                    b.HasOne("Shop_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.HasOne("Shop_Models.Entities.Voucher", "Vouchers")
                        .WithMany("HoaDon")
                        .HasForeignKey("VoucherId");

                    b.Navigation("NguoiDung");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucTTChiTiet", b =>
                {
                    b.HasOne("Shop_Models.Entities.HoaDon", "HoaDon")
                        .WithMany("PhuongThucTTChiTiet")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("PhuongThucTTChiTiets")
                        .HasForeignKey("PhuongThucThanhToanId");

                    b.Navigation("HoaDon");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPhamYeuThich", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("SanPhamYeuThich")
                        .HasForeignKey("ChiTietSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Shop_Models.Entities.ThongKe", b =>
                {
                    b.HasOne("Shop_Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("ThongKes")
                        .HasForeignKey("ChiTietSanPhamId");

                    b.HasOne("Shop_Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ThongKes")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChatLieu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.ChiTietSanPham", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("SanPhamYeuThich");

                    b.Navigation("ThongKes");
                });

            modelBuilder.Entity("Shop_Models.Entities.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("Shop_Models.Entities.HoaDon", b =>
                {
                    b.Navigation("PhuongThucTTChiTiet");

                    b.Navigation("ThongKes");
                });

            modelBuilder.Entity("Shop_Models.Entities.Khuyenmai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("Shop_Models.Entities.Loai", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("PhuongThucTTChiTiets");
                });

            modelBuilder.Entity("Shop_Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.ThuongHieu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Shop_Models.Entities.Voucher", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Shop_Models.Entities.XuatXu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
